-- CLAUSES IN SQL
---------------------
SP_HELP EMP
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE='BASE TABLE'
DROP TABLE EMPLOYEE

CREATE TABLE EMPLOYEE (
    employee_id INT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    department VARCHAR(50),
    salary DECIMAL(10, 2),
    hire_date DATE
);


INSERT INTO EMPLOYEE (employee_id, first_name, last_name, department, salary, hire_date)
VALUES
    (102, 'Jane', 'Smith', 'IT', 75000.00, '2024-05-20'),
    (103, 'Peter', 'Jones', 'Sales', 50000.00, '2025-02-10'),
    (104, 'Mary', 'Davis', 'HR', 55000.00, '2024-08-01'),
    (105, 'Robert', 'Miller', 'Marketing', 62000.00, '2024-06-15'),
    (106, 'Susan', 'Wilson', 'IT', 81000.00, '2023-11-01'),
    (107, 'Chris', 'Taylor', 'Finance', 90000.00, '2025-03-22'),
    (108, 'Patricia', 'Clark', 'HR', 58000.00, '2024-09-10'),
    (109, 'Michael', 'Garcia', 'Sales', 53000.00, '2025-01-05'),
    (110, 'Jennifer', 'Rodriguez', 'Finance', 92000.00, '2024-04-18'),
    (111, 'William', 'Hernandez', 'Operations', 65000.00, '2023-12-01');

    SELECT * FROM EMPLOYEE;

    ALTER TABLE EMPLOYEE ADD DEPTNO VARCHAR(20);

    UPDATE EMPLOYEE SET DEPTNO = 10 WHERE DEPARTMENT='IT';
    UPDATE EMPLOYEE SET DEPTNO = 20 WHERE DEPARTMENT='Sales';
    UPDATE EMPLOYEE SET DEPTNO = 30 WHERE DEPARTMENT='HR';
    UPDATE EMPLOYEE SET DEPTNO = 30 WHERE DEPARTMENT='FINANCE';
    UPDATE EMPLOYEE SET DEPTNO = 20 WHERE DEPARTMENT='OPERATIONS';
    UPDATE EMPLOYEE SET DEPTNO = 10 WHERE DEPARTMENT='MARKETING';


    SP_HELP EMPLOYEE;

   -- GROUP BY(EXTRACT TOTAL_SALARY OF EMPLOYEES OF A PARTICULAR DEPT)
   SELECT E.DEPARTMENT AS DEPT,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE E GROUP BY department

   -- COUNT NUMBER OF EMPLOYEES WORKING IN EACH DEPARTMENT AND SHOW THEM IN DEPT AND NOOFEMP COLUMN
   SELECT E.DEPARTMENT AS DEPT,COUNT(*) AS NOOFEMP FROM EMPLOYEE E GROUP BY DEPARTMENT

   SELECT DEPARTMENT,COUNT(*) NUMOFEMPLOYEE FROM EMPLOYEE E GROUP BY DEPARTMENT

   -- FIND MAX,MIN AND AVG SALARY FOR EACH DEPARTMENT
   SELECT DEPARTMENT,MAX(SALARY) MAXI,MIN(SALARY) MINI,AVG(SALARY) AVGE
   FROM EMPLOYEE
   GROUP BY DEPARTMENT

   SELECT * FROM EMPLOYEE

   -- SHOW THE DEPARTMENT AND DEPTNO AND NUM OF PEOPLE WORKING IN THAT DEPARTMENT
   SELECT DEPARTMENT,COUNT(*) NUMOFEMPLOYEE,DEPTNO FROM EMPLOYEE
   GROUP BY DEPARTMENT,DEPTNO;

-- HAVING CLAUSE
------------------

   -- FINDOUT DEPARTMENTS,EMPLOYEECOUNT WHERE EMPLOYEE COUNT IS LESS THAN 2
   SELECT DEPARTMENT,COUNT(*) EMPCOUNT FROM EMPLOYEE GROUP BY DEPARTMENT
   HAVING COUNT(*) < 2;

   -- FINDOUT DEPARTMENTS WHERE TOTAL SAL OF EMP IS > THAN 1 LAKH
   SELECT DEPARTMENT,SUM(SALARY) AS SAL FROM EMPLOYEE GROUP BY DEPARTMENT
   HAVING SUM(SALARY) > 100000