-- CURSORS IN SQL

-- 1)IMPLICIT CURSOR
-----------------------
SELECT * FROM EMPLOYEE
PRINT @@ROWCOUNT -- 0

DELETE FROM EMPLOYEE WHERE employee_id=111;
PRINT @@ROWCOUNT -- 1

INSERT INTO EMPLOYEE VALUES(110,'Lara','Brian','Marketing',90000,'2021-09-12',10); --110 is already present
PRINT @@ERROR -- 2627

-- 2)EXPLICIT CURSOR
-----------------------
DECLARE EMP_CURSOR CURSOR FOR
SELECT first_name,salary FROM EMPLOYEE;

OPEN EMP_CURSOR;

DECLARE @NAME VARCHAR(50), @SALARY MONEY;

FETCH NEXT FROM EMP_CURSOR INTO @NAME,@SALARY;

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'Employee: '+@NAME+' Salary: '+CAST(@SALARY AS VARCHAR);
	FETCH NEXT FROM EMP_CURSOR INTO @Name,@Salary;
END

CLOSE EMP_CURSOR;
DEALLOCATE EMP_CURSOR;
