use MYCLASSDB

CREATE TABLE STUDENT(STID INT, SNAME VARCHAR(40), SFEE DECIMAL(6,2), AGE TINYINT)

SP_RENAME 'STUDENT.SID','STID'

SP_HELP STUDENT

ALTER TABLE STUDENT ALTER COLUMN SFEE DECIMAL(6,2)

INSERT INTO STUDENT VALUES(102,'RAMESH',9000.00,23)

INSERT INTO STUDENT(STID,SNAME,AGE) VALUES (103,'RAHUL',24);

SELECT * FROM STUDENT

INSERT STUDENT VALUES(104,'HARISH',8900,25);

INSERT STUDENT(STID,SNAME,SFEE) VALUES (105,'KARIM',6000);

UPDATE STUDENT SET SFEE=8000 WHERE STID = 103

UPDATE STUDENT SET AGE = 26 WHERE AGE IS NULL;

UPDATE STUDENT SET SFEE = 7500

DELETE FROM STUDENT WHERE SNAME = 'KARIM'

UPDATE STUDENT SET AGE=NULL WHERE STID=104

DELETE FROM STUDENT WHERE AGE IS NULL

DELETE FROM STUDENT

SELECT * FROM STUDENT