--IDENTITY(SEED,INCREMENT)
---------------------------
USE MYCLASSDB

CREATE TABLE EMP(EID INT IDENTITY,ENAME VARCHAR(40),SALARY MONEY, SNO INT IDENTITY);

CREATE TABLE EMP(EID INT IDENTITY,ENAME VARCHAR(40),SALARY MONEY, SNO INT);

SP_HELP EMP;

ALTER TABLE EMP DROP COLUMN SNO;

INSERT INTO EMP VALUES(1,'ASHISH',78000) -- NOT ALLOWED(AS IDENTITY APPLIED TO EID)

INSERT INTO EMP VALUES('ASHISH',78000) -- ALLOWED

INSERT INTO EMP(ENAME,SALARY) VALUES('BOY',7000)

UPDATE EMP SET ENAME='HARRY',SALARY=80000 WHERE EID=2

INSERT INTO EMP VALUES('JACK',45000)

SELECT * FROM EMP;

--EX:- USER PROVIDED SEED & INCREMENT FOR IDENTITY

CREATE TABLE EMP1(EID INT IDENTITY(100,5),ENAME VARCHAR(40),SALARY MONEY);

INSERT INTO EMP1 VALUES('ASHISH',78000)

INSERT INTO EMP1 VALUES('JACK',45000)

INSERT INTO EMP1 VALUES('tACK',45000),('ZACK',45000)

SELECT * FROM EMP1;

-- PROVIDE VALUE EXPLICITLY FOR IDENTITY COLUMN(EID)
-- SYNTAX:- SET IDENTITY_INSERT<TABLE_NAME> OFF/ON

SET IDENTITY_INSERT EMP1 ON
INSERT INTO EMP1(EID,ENAME,SALARY) VALUES(108,'ROB',58000)

SET IDENTITY_INSERT EMP1 OFF
INSERT INTO EMP1(EID,ENAME,SALARY) VALUES(109,'FOROB',58000) --NOT ALLOWED AFTER IDENTITY_INSERT OFF

SP_HELP EMP1

