
--ANSI FORMAT JOIN
------------------
-- -> INNER JOIN
-- -> OUTER JOIN
--		|- LEFT OUTER JOIN
--		|- RIGHT OUTER JOIN
--		|- FULL OUTER JOIN
-- -> CROSS JOIN
-- -> NATURAL JOIN

--NON-ANSI FORMAT JOIN
----------------------
-- -> EQUI JOIN
-- -> NON-EQUI JOIN
-- -> SELF JOIN
USE MYCLASSDB
DROP TABLE STUDENT;

select * from sys.tables
EXEC SP_TABLES @table_type = "'TABLE'"

CREATE TABLE STUDENT(STID INT,SNAME VARCHAR(40),SEMAILID VARCHAR(50),COURSEID INT);

CREATE TABLE COURSE(COURSEID INT,CNAME VARCHAR(40),CFEE DECIMAL(6,2));

-- INNER JOIN
---------------
-- QUERY TO RETRIVE STUDENT,COURSE DETAILS BASED ON COURSEID USING INNER JOIN
SELECT * FROM STUDENT INNER JOIN COURSE ON STUDENT.COURSEID = COURSE.COURSEID;

-- OUTER JOIN
---------------
-- LEFT OUTER JOIN :-
SELECT * FROM STUDENT S LEFT OUTER JOIN COURSE C ON S.COURSEID = C.COURSEID; 
-- ABOVE RETRIEVES MATCHING DATA FROM BOTH TABLES AND UN-MATCHING DATA ONLY FROM STUDENT TABLE.

-- RIGHT OUTER JOIN :-
SELECT * FROM STUDENT S RIGHT OUTER JOIN COURSE C ON S.COURSEID = C.COURSEID; 
-- ABOVE RETRIEVES MATCHING DATA FROM BOTH TABLES AND UN-MATCHING DATA ONLY FROM COURSE TABLE.

-- FULL OUTER JOIN :-
SELECT * FROM STUDENT S FULL OUTER JOIN COURSE C ON S.COURSEID = C.COURSEID;
-- ABOVE RETRIEVES MATCHING DATA AND UN-MATCHING DATA FROM ALL TABLES.

-- CROSS JOIN:-
----------------
SELECT * FROM STUDENT CROSS JOIN COURSE;
-- RETIEVES ALL POSSIBLE COMBINATION OF ROWS FROM STUDENT & COURSE TABLE(DOES CARTESIAN PRODUCT(3 x 4))

-- NON-ANSI FORMAT JOINS:-(USING WHERE FOR SPECIFYING CONDITIONS)
-- EQUI JOIN:-
-----------------
SELECT * FROM STUDENT S,COURSE C WHERE S.COURSEID = C.COURSEID

-- NON-EQUI JOIN
------------------------
SELECT * FROM STUDENT S,COURSE C WHERE S.COURSEID > C.COURSEID

SELECT * FROM STUDENT;
SELECT * FROM COURSE;

-- SELF JOIN
--------------
-- COMPARES COLUMN VALUES WITHIN THE SAME TABLE
SELECT * FROM SYS.tables;
DROP TABLE EMPLOYEE

--EXAMPLE 1:-
CREATE TABLE EMPLOYEE(EID INT,ENAME VARCHAR(20),MID INT);
INSERT EMPLOYEE VALUES(1,'ALICE',NULL),(2,'BOB',1),(3,'CHARLIE',1),(4,'DAVID',2)

SELECT * FROM EMPLOYEE

-- WRITE A QUERY TO RETRIVE EMPLOYEE NAME AND THEIR MANAGER NAME
SELECT e.ENAME AS EMPLOYEE,m.ENAME AS MANAGER
FROM EMPLOYEE e LEFT JOIN EMPLOYEE m
ON e.MID = m.EID;

--EXAMPLE 2:-
CREATE TABLE EMPLOYEE2(EID INT,ENAME VARCHAR(20),SALARY MONEY,MID INT);
INSERT EMPLOYEE2 VALUES(101,'SMITH',8000,101),(102,'WARNER',11000,108),(103,'JMES',18000,109),(104,'SCOTT',82000,104),(105,'BLAKE',34000,110),(106,'ADAMS',8000,106)

-- GET DETAILS OF PERSONS WHOSE SALARY IS SAME
SELECT e1.ENAME AS EMP1,e2.SALARY AS SALARY
FROM EMPLOYEE2 e1 INNER JOIN EMPLOYEE2 e2
ON e1.SALARY = e2.SALARY
WHERE e1.EID <> e2.EID; -- this ensures that same rows with same EID arent match with each other

SELECT * FROM EMPLOYEE2;

-- GET DETAILS OF EMPLOYEE WHO IS GETTING SAME SALARY AS SMITH
SELECT * FROM EMPLOYEE2 WHERE SALARY = (SELECT SALARY FROM EMPLOYEE2 WHERE ENAME='SMITH')

SELECT M.ENAME AS EMP, S.SALARY AS SAL
FROM EMPLOYEE2 M INNER JOIN EMPLOYEE2 S
ON S.ENAME='SMITH'
WHERE M.EID <> S.EID

ALTER TABLE EMPLOYEE2 DROP COLUMN MID;