-- PRIMARY KEY AND FOREIGN KEY CONSTRINTS

-- STEP 1:
CREATE TABLE DEPARTMENT(DEPTNO INT PRIMARY KEY, DNAME VARCHAR(20),LOCATION VARCHAR(40)); --PARENT TABLE
-- STEP 2:
INSERT INTO DEPARTMENT VALUES(10,'DBA','HYD'),(20,'SAP','MUMBAI'),(30,'HR','PUNE')
-- STEP 3:
CREATE TABLE EMPLOYEE(EMPID INT, ENAME VARCHAR(40), SALARY MONEY,
DEPTNO INT FOREIGN KEY REFERENCES DEPARTMENT(DEPTNO));  --CHILD TABLE

-- TEST TO CONFIRM IF RELATIONSHIP WAS ESTABLISHED
INSERT EMPLOYEE VALUES(101,'ADAMS',56000,10);
INSERT EMPLOYEE VALUES(102,'JAMES',45000,20); -- THESE ARE ACCEPTED
INSERT EMPLOYEE VALUES(103,'SCOTT',23000,30);

INSERT EMPLOYEE VALUES(104,'HARRY',63000,40); -- NOT ACCEPTED AS 40 IS NOT THERE IN PARENT TABLE DEPTNO COLUMN

SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;