select * from employee;

-- ROW_NUMBER(), RANK(), DENSE_RANK
-- PARTITION BY IS OPTIONAL HERE BUT ORDER BY IS MANDATORY(BECAUSE RANKING DEPENDS UPON THAT)

SELECT first_name,salary,department,
ROW_NUMBER() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROWNUM
FROM EMPLOYEE;

SELECT first_name,salary,department,
RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROWNUM
FROM EMPLOYEE;

SELECT first_name,salary,department,
DENSE_RANK() OVER(PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS ROWNUM
FROM EMPLOYEE;

UPDATE EMPLOYEE SET salary=55000 WHERE DEPARTMENT='Operations';