--ROLLUP AND CUBE CLAUSE

SELECT TABLE_NAME FROM MYCLASSDB.INFORMATION_SCHEMA.Tables WHERE TABLE_TYPE = 'BASE TABLE'
SELECT * FROM EMPLOYEE;
SELECT DEPARTMENT,COUNT(*) FROM EMPLOYEE GROUP BY ROLLUP(DEPARTMENT);
SELECT DEPARTMENT,COUNT(*),DEPTNO FROM EMPLOYEE GROUP BY ROLLUP(DEPARTMENT,DEPTNO);

SELECT DEPARTMENT,COUNT(*),DEPTNO FROM EMPLOYEE GROUP BY CUBE(DEPARTMENT,DEPTNO);