-- scalar valued functions
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

--SCALAR VALUED FUNCTIONS
SELECT * FROM EMP;

-- CREATE A SCALAR VALUED FUNCN TO RETURN THE GROSS SAL OF EMP
-- HRA - 10%, DA - 20%, PF - 10%
CREATE FUNCTION F_GRSAL(@EID INT)
RETURNS MONEY
AS
BEGIN
DECLARE @BASIC MONEY, @HRA MONEY, @DA MONEY, @PF MONEY, @GROSS MONEY
SELECT @BASIC=SALARY FROM EMP WHERE EID=@EID
SET @HRA = @BASIC * 0.1
SET @DA = @BASIC * 0.2
SET @PF = @BASIC * 0.1
SET @GROSS = @HRA+@DA+@PF+@BASIC
RETURN @GROSS
END

--CALLING THE SCALAR VALUED FUNCTION
SELECT dbo.F_GRSAL(3);

