-- SET OPERATORS
----------------
-- UNION, UNION ALL, INTERSECT, EXCEPT

USE MYCLASSDB

CREATE TABLE EMP_HYD(EID INT,ENAME VARCHAR(20),SALARY MONEY)

CREATE TABLE EMP_CHENNAI(EID INT,ENAME VARCHAR(20),SALARY MONEY)

-- UNION

SELECT * FROM EMP_HYD UNION SELECT * FROM EMP_CHENNAI

SELECT SALARY FROM EMP_HYD UNION SELECT SALARY FROM EMP_CHENNAI

SELECT EID,ENAME FROM EMP_HYD UNION SELECT EID,ENAME FROM EMP_CHENNAI

-- UNION ALL

SELECT * FROM EMP_HYD
UNION ALL
SELECT * FROM EMP_CHENNAI

-- INTERSECT
SELECT * FROM EMP_HYD
INTERSECT
SELECT * FROM EMP_CHENNAI

-- EXCEPT
SELECT * FROM EMP_CHENNAI
EXCEPT
SELECT * FROM EMP_HYD

SELECT * FROM EMP_HYD
EXCEPT
SELECT * FROM EMP_CHENNAI

SELECT * FROM EMP_HYD
SELECT * FROM EMP_CHENNAI