-- SUB BLOCKS IN T-SQL

-- 1. STORED PROCEDURE
------------------------
CREATE PROCEDURE SP1
AS
BEGIN
SELECT * FROM EMPLOYEE
END;

-- CALLING THE PROCEDURE
EXEC SP1;

-- STORED PROCEDURE WITH "IN" PARAMETER
-- CREATE A PROCEDURE TO INPUT THE EMPLOYEE DETAILS INTO A TABLE
CREATE TABLE EMP2(EID INT,ENAME VARCHAR(30),ESAL MONEY);

CREATE PROCEDURE INSERTEMPLOYEE(@EID INT,@ENAME VARCHAR(50),@ESAL MONEY)
AS
BEGIN
INSERT INTO EMP2 VALUES(@EID,@ENAME,@ESAL)
END

-- CALL INSERTEMPLOYEE PROCEDURE
EXEC INSERTEMPLOYEE 100,'ASHISH',90000;
EXEC INSERTEMPLOYEE 101,'RAJESH',78000
EXEC INSERTEMPLOYEE 102,'MUKESH',98000


SELECT * FROM EMP2;

-- STORED PROCEDURE WITH "OUT" PARAMETER
CREATE PROCEDURE SPEMPPFANDTAXCALCULATOR(@EID INT,@PF INT OUT,@PT INT OUT)
AS
BEGIN
DECLARE @SAL MONEY
SELECT @SAL=SALARY FROM EMPLOYEE WHERE employee_id=@EID
SET @PF = @SAL*0.1
SET @PT = @SAL*0.2
END

-- CALLING THE ABOVE STORED PROCEDURE
---------------------------------------
DECLARE @bPF INT,@bPT INT
EXEC SPEMPPFANDTAXCALCULATOR 102,@bPF OUT,@bPT OUT
PRINT 'PROVIDENT FUND AMOUNT IS: '+CAST(@bPF AS VARCHAR)
PRINT 'PROFESSIONAL TAX IS: '+CAST(@bPT AS VARCHAR)

-- DROP STORED PROCEDURE SPEMPPFANDTAXCALCULATOR
-------------------------------------------------
DROP PROCEDURE SPEMPPFANDTAXCALCULATOR;