-- SUB QUERY / NESTED QUERY
-- 1) NON-CORRELATED SUBQUERY
		-- SIMPLE / SINGLE ROW SUBQUERY
		-- MULTIPLE ROW SUBQUERY
-- 2) CORRELATED SUBQUERY
USE MYCLASSDB;

-- SIMPLE / SINGLE ROW SUBQUERY
SELECT * FROM EMP WHERE SALARY=(SELECT MAX(SALARY) FROM EMP);
SP_HELP EMP;

-- MULTIPLE ROW SUBQUERY
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE DEPARTMENT IN
(SELECT DEPARTMENT FROM EMPLOYEE WHERE first_name IN('Jane','Peter'));

-- CORRELATED SUBQUERY
-- WAQ TO FIND NTH HIGHEST SALARY FROM EMPLOYEE TABLE
DECLARE @N INT=1;

SELECT * FROM EMPLOYEE E1
WHERE @N - 1=(
SELECT COUNT(DISTINCT E2.SALARY) FROM EMPLOYEE E2
WHERE E2.salary > E1.salary);  -- THE INNER QUERY COUNTS THE DISTINCT NUMBER OF SALARIES THATS GREATER THAN THE
								-- SALARY OF CURRENT ROW.

SELECT * FROM EMPLOYEE;