-- TABLE VALUED FUNCTION
-- FUNCTION WILL RETURN MORE THAN ONE VALUE OR MORE THAN ONE COLUMN VALUE FROM THE TABLE

SELECT * FROM EMPLOYEE;

-- CREATE A TVF TO ACCEPT DEPTNAME AS A PARAMETER AND RETURN LIST OF EMPLOYEES WORKING IN THAT DEPT
CREATE FUNCTION LIST_EMP(@DEPTNAME VARCHAR(30))
RETURNS TABLE
AS
RETURN(SELECT * FROM EMPLOYEE WHERE DEPARTMENT=@DEPTNAME)

--CALLING THE TVF
SELECT * FROM LIST_EMP('IT')