CREATE TABLE BRANCH(BCODE INT,BNAME VARCHAR(20),LOCATION VARCHAR(50))

BEGIN TRANSACTION
ROLLBACK

INSERT INTO BRANCH VALUES(1001,'SBI','HYD')
UPDATE BRANCH SET LOCATION='MUMBAI' WHERE BCODE=1001
DELETE FROM BRANCH WHERE BCODE=1001
-- THE DML OPERATIONS(INSERT, UPDATE, DELETE) ARE BY DEFAUT AUTO COMMIT OPERATIONS. SO ROLLBACK WONT WORK.

SELECT * FROM BRANCH

-- TCL COMMANDS
----------------
-- BEGIN TRANSACTION
-- COMMIT
-- ROLLBACK
-- SAVEPOINT
EX1:
BEGIN TRANSACTION
INSERT INTO BRANCH VALUES(1002,'HDFC','HYD')
COMMIT

EX2:
BEGIN TRANSACTION
UPDATE BRANCH SET LOCATION='HYD' WHERE BCODE=1002
COMMIT

EX3:
BEGIN TRANSACTION
DELETE FROM BRANCH WHERE BCODE=1002

BEGIN TRANSACTION
ROLLBACK

EX4:
BEGIN TRANSACTION
DELETE FROM BRANCH WHERE BCODE=1001
DELETE FROM BRANCH WHERE BCODE=1002

SAVE TRANSACTION S1
DELETE FROM BRANCH WHERE BCODE=1003

BEGIN TRANSACTION
ROLLBACK TRANSACTION S1

SELECT * FROM BRANCH

