-- UNIQUE, NOT NULL, CHECK

-- UNIQUE
CREATE TABLE TEST1(SNO INT UNIQUE,LOCATION VARCHAR(50) UNIQUE);

SELECT * FROM TEST1;


-- TESTING
INSERT INTO TEST1 VALUES(101,'HYD')
INSERT INTO TEST1 VALUES(102,'UP')
INSERT INTO TEST1 VALUES(103,'NULL')

-- NOT NULL
CREATE TABLE TEST2(SNO INT NOT NULL,LOCATION VARCHAR(50) NOT NULL);

-- TESTING
INSERT INTO TEST2 VALUES(101,'HYD')
INSERT INTO TEST2 VALUES(101,'HYD')
INSERT INTO TEST1 VALUES(NULL,'HYD') -- NOT ALLOWED

SELECT * FROM TEST2;

-- CHECK
CREATE TABLE TEST3(EID INT,ESAL MONEY CHECK(ESAL<=50000));

-- TESTING
INSERT INTO TEST3 VALUES(100,8900); -- ALLOWED
INSERT INTO TEST3 VALUES(102,89000); -- NOT ALLOWED

SELECT * FROM TEST3;




