--VIEWS IN SQL SERVER
--VIEWS ARE VIRTUAL TABLES(WE DONT INTERACT WITH BASE TABLE BUT WITH VIEWS)

--1)SIMPLE VALUES(UPDATABLE VIEWS)
----------------------------------
--SUPPORTS DML OPERATION

CREATE VIEW EMPVIEW AS
SELECT * FROM EMP;

TESTING:
INSERT INTO EMPVIEW VALUES('PRANAYA',89332); --UPDATES THE VIEW AND THE BASE TABLE

UPDATE EMPVIEW SET SALARY=120000 WHERE ENAME='ASHISH'

DELETE FROM EMPVIEW WHERE EID=5

SELECT * FROM EMPVIEW;
SELECT * FROM EMP;

--2)COMPLEX VIEW(NON-UPDATABLE VIEW)
------------------------------------
-- DOESN'T SUPPORT DML OPERATIONS.
-- SUPPORTS JOIN

-- COMBINE EMP_HYD AND EMP_CHENNAI TABLE TO CREATE A COMPLEX VIEW
CREATE VIEW CV1 AS
SELECT * FROM EMP_HYD
UNION
SELECT * FROM EMP_CHENNAI;

TESTING:
SELECT * FROM CV1;

INSERT INTO CV1 VALUES(107,'MILLER',54000); -- NOT ALLOWED

UPDATE CV1 SET ENAME='ASHISH' WHERE EID=101; -- NOT ALLOWED

DELETE FROM CV1 WHERE EID=101; --NOT ALLOWED

SELECT * FROM EMP_HYD;
SELECT * FROM EMP_CHENNAI;
